### ISSUE TITLE
character set

### ISSUE THREAD

**Issue by jreiser** [fyngyrz/aa_macro#7]
The documentation must contain an explicit statement and discussion of character set.  A Linux user will expect  UTF-8.  A user of MS Windows will expect selectable codepage (with a default preference of codepage-1250 or whatever it is)  <b>and</b> UCS-16 ("Unicode").  In Japan, JIS.

Common to all of these is the difference between a byte and a character.  aamacro must never assume that they are the same.  In particular, the test cases must exercise this point.

**Comment by fyngyrz** [comment]
I'll add that to the docs. Good call.

[Here it is.](http://ourtimelines.com/aamacrodoc/appendixa.html#ixref232)
